/gun/energy 500 MeV
/blocks/nBlocks 1
/run/reinitializeGeometry
/run/beamOn 1000000
/blocks/nBlocks 2
/run/reinitializeGeometry
/run/beamOn 1000000
/blocks/nBlocks 3
/run/reinitializeGeometry
/run/beamOn 1000000
/blocks/nBlocks 4
/run/reinitializeGeometry
/run/beamOn 1000000
/blocks/nBlocks 5
/run/reinitializeGeometry
/run/beamOn 1000000
/blocks/nBlocks 6
/run/reinitializeGeometry
/run/beamOn 1000000